# Generated by Django 5.1.6 on 2026-03-19 04:23

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('securedAnalyticsApp', '0002_slecategory_slequestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLECategoryProxy',
            fields=[
            ],
            options={
                'verbose_name': 'SLE Category',
                'verbose_name_plural': 'SLE Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('securedAnalyticsApp.slecategory',),
        ),
        migrations.CreateModel(
            name='SLEQuestionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'SLE Question',
                'verbose_name_plural': 'SLE Questions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('securedAnalyticsApp.slequestion',),
        ),
        migrations.CreateModel(
            name='SLEResponseProxy',
            fields=[
            ],
            options={
                'verbose_name': 'SLE Response',
                'verbose_name_plural': 'SLE Responses',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('securedAnalyticsApp.sleresponse',),
        ),
        migrations.CreateModel(
            name='SupervisorLeadershipEngagementProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Supervisor Leadership Engagement',
                'verbose_name_plural': 'Supervisor Leadership Engagements',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('securedAnalyticsApp.supervisorleadershipengagement',),
        ),
    ]
