# Generated by Django 5.1.6 on 2026-03-19 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SLEResponseProxy',
        ),
    ]
