# Generated by Django 5.1.6 on 2026-03-19 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_delete_sleresponseproxy'),
        ('securedAnalyticsApp', '0005_mentalemotionalresilience'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalEmotionalResilienceProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Mental and Emotional Resilience in Leadership',
                'verbose_name_plural': 'Mental and Emotional Resilience in Leadership',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('securedAnalyticsApp.mentalemotionalresilience',),
        ),
    ]
