# Generated by Django 5.1.6 on 2026-03-19 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_mentalemotionalresilienceproxy'),
        ('securedAnalyticsApp', '0006_mercategory_merquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MERCategoryProxy',
            fields=[
            ],
            options={
                'verbose_name': 'MER Category',
                'verbose_name_plural': 'MER Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('securedAnalyticsApp.mercategory',),
        ),
        migrations.CreateModel(
            name='MERQuestionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'MER Question',
                'verbose_name_plural': 'MER Questions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('securedAnalyticsApp.merquestion',),
        ),
    ]
