# Generated by Django 5.1.6 on 2026-03-19 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_mercategoryproxy_merquestionproxy'),
        ('securedAnalyticsApp', '0007_officerwellbeing_owbcategory_owbquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficerWellbeingProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Officer Wellbeing',
                'verbose_name_plural': 'Officer Wellbeing',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('securedAnalyticsApp.officerwellbeing',),
        ),
        migrations.CreateModel(
            name='OWBCategoryProxy',
            fields=[
            ],
            options={
                'verbose_name': '\xa0\xa0\xa0\xa0OWB Category',
                'verbose_name_plural': '\xa0\xa0\xa0\xa0OWB Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('securedAnalyticsApp.owbcategory',),
        ),
        migrations.CreateModel(
            name='OWBQuestionProxy',
            fields=[
            ],
            options={
                'verbose_name': '\xa0\xa0\xa0\xa0OWB Question',
                'verbose_name_plural': '\xa0\xa0\xa0\xa0OWB Questions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('securedAnalyticsApp.owbquestion',),
        ),
        migrations.AlterModelOptions(
            name='mercategoryproxy',
            options={'verbose_name': '\xa0\xa0\xa0\xa0MER Category', 'verbose_name_plural': '\xa0\xa0\xa0\xa0MER Categories'},
        ),
        migrations.AlterModelOptions(
            name='merquestionproxy',
            options={'verbose_name': '\xa0\xa0\xa0\xa0MER Question', 'verbose_name_plural': '\xa0\xa0\xa0\xa0MER Questions'},
        ),
        migrations.AlterModelOptions(
            name='slecategoryproxy',
            options={'verbose_name': '\xa0\xa0\xa0\xa0SLE Category', 'verbose_name_plural': '\xa0\xa0\xa0\xa0SLE Categories'},
        ),
        migrations.AlterModelOptions(
            name='slequestionproxy',
            options={'verbose_name': '\xa0\xa0\xa0\xa0SLE Question', 'verbose_name_plural': '\xa0\xa0\xa0\xa0SLE Questions'},
        ),
    ]
