# Generated by Django 5.1.6 on 2026-03-19 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_officerwellbeingproxy_owbcategoryproxy_and_more'),
        ('securedAnalyticsApp', '0008_pswcategory_psychologicalsafety_pswquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSWCategoryProxy',
            fields=[
            ],
            options={
                'verbose_name': '\xa0\xa0\xa0\xa0PSW Category',
                'verbose_name_plural': '\xa0\xa0\xa0\xa0PSW Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('securedAnalyticsApp.pswcategory',),
        ),
        migrations.CreateModel(
            name='PSWQuestionProxy',
            fields=[
            ],
            options={
                'verbose_name': '\xa0\xa0\xa0\xa0PSW Question',
                'verbose_name_plural': '\xa0\xa0\xa0\xa0PSW Questions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('securedAnalyticsApp.pswquestion',),
        ),
        migrations.CreateModel(
            name='PsychologicalSafetyProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Psychological Safety in the Workplace',
                'verbose_name_plural': 'Psychological Safety in the Workplace',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('securedAnalyticsApp.psychologicalsafety',),
        ),
    ]
