# Generated by Django 5.1.6 on 2026-03-19 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_pswcategoryproxy_pswquestionproxy_and_more'),
        ('securedAnalyticsApp', '0009_oclcategory_organizationalculturechange_oclquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCLCategoryProxy',
            fields=[
            ],
            options={
                'verbose_name': '\xa0\xa0\xa0\xa0OCL Category',
                'verbose_name_plural': '\xa0\xa0\xa0\xa0OCL Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('securedAnalyticsApp.oclcategory',),
        ),
        migrations.CreateModel(
            name='OCLQuestionProxy',
            fields=[
            ],
            options={
                'verbose_name': '\xa0\xa0\xa0\xa0OCL Question',
                'verbose_name_plural': '\xa0\xa0\xa0\xa0OCL Questions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('securedAnalyticsApp.oclquestion',),
        ),
        migrations.CreateModel(
            name='OrganizationalCultureChangeProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Organizational Culture and Leadership Change',
                'verbose_name_plural': 'Organizational Culture and Leadership Change',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('securedAnalyticsApp.organizationalculturechange',),
        ),
    ]
