# Generated by Django 5.1.6 on 2026-03-17 01:03

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import securedAnalyticsApp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('name_suffix', models.CharField(blank=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_id', models.CharField(default=securedAnalyticsApp.models.generate_anonymous_id, editable=False, max_length=10, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('ethnicity', models.CharField(blank=True, choices=[('Asian', 'Asian'), ('Black', 'Black'), ('Hispanic', 'Hispanic'), ('Native American', 'Native American'), ('Pacific Islander', 'Pacific Islander'), ('White', 'White'), ('Mixed Race', 'Mixed Race'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], default='Other', max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('', '— Select —'), ('Male', 'Male'), ('Female', 'Female')], default='', max_length=10)),
                ('rank', models.CharField(blank=True, choices=[('', '— Select —'), ('Officer', 'Officer'), ('Deputy', 'Deputy'), ('trooper', 'trooper'), ('Constable', 'Constable'), ('Detective', 'Detective'), ('Investigator', 'Investigator'), ('Deputy Inspector', 'Deputy Inspector'), ('Corporal', 'Corporal'), ('Senior Officer', 'Senior Officer'), ('Sergeant', 'Sergeant'), ('Staff Sergeant', 'Staff Sergeant'), ('Lieutenant', 'Lieutenant'), ('Captain', 'Captain'), ('Commander', 'Commander'), ('Major', 'Major'), ('Deputy Chief', 'Deputy Chief'), ('Assistant Chief', 'Assistant Chief'), ('Lieutenant Colonel', 'Lieutenant Colonel'), ('Colonel', 'Colonel'), ('Undersheriff', 'Undersheriff'), ('Chief of Police', 'Chief of Police'), ('Sheriff', 'Sheriff'), ('Commissioner', 'Commissioner'), ('Superintendent', 'Superintendent')], default='', max_length=30)),
                ('years_of_service', models.CharField(blank=True, choices=[('', '— Select —'), ('0-2', '0–2 years'), ('2-3', '2–3 years'), ('3-5', '3–5 years'), ('5-7', '5–7 years')], default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('address_type', models.CharField(choices=[('Home', 'Home'), ('Work', 'Work'), ('Other', 'Other')], default='Home', max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='securedAnalyticsApp.person')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
