# Generated by Django 5.1.6 on 2026-03-19 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securedAnalyticsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLECategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeral', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII')], max_length=4, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'SLE Category',
                'verbose_name_plural': 'SLE Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SLEQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('text', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='securedAnalyticsApp.slecategory')),
            ],
            options={
                'verbose_name': 'SLE Question',
                'verbose_name_plural': 'SLE Questions',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='SupervisorLeadershipEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sle_assessments', to='securedAnalyticsApp.person')),
            ],
            options={
                'verbose_name': 'Supervisor Leadership Engagement',
                'verbose_name_plural': 'Supervisor Leadership Engagements',
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='SLEResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')])),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='securedAnalyticsApp.slequestion')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='securedAnalyticsApp.supervisorleadershipengagement')),
            ],
            options={
                'verbose_name': 'SLE Response',
                'verbose_name_plural': 'SLE Responses',
                'ordering': ['question__number'],
                'constraints': [models.UniqueConstraint(fields=('assessment', 'question'), name='unique_sle_response_per_question')],
            },
        ),
    ]
