# Generated by Django 5.1.6 on 2026-03-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securedAnalyticsApp', '0002_slecategory_slequestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisorleadershipengagement',
            name='person',
        ),
        migrations.AddField(
            model_name='supervisorleadershipengagement',
            name='title',
            field=models.CharField(default="Supervisor's Leadership Engagement", max_length=255),
        ),
    ]
