# Generated by Django 5.1.6 on 2026-03-19 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securedAnalyticsApp', '0003_remove_supervisorleadershipengagement_person_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SLEResponse',
        ),
    ]
