# Generated by Django 5.1.6 on 2026-03-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securedAnalyticsApp', '0004_delete_sleresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalEmotionalResilience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Mental and Emotional Resilience in Leadership', max_length=255)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mental and Emotional Resilience in Leadership',
                'verbose_name_plural': 'Mental and Emotional Resilience in Leadership',
                'ordering': ['-assessed_at'],
            },
        ),
    ]
