# Generated by Django 5.1.6 on 2026-03-19 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securedAnalyticsApp', '0005_mentalemotionalresilience'),
    ]

    operations = [
        migrations.CreateModel(
            name='MERCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeral', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII')], max_length=4, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'MER Category',
                'verbose_name_plural': 'MER Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MERQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('text', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='securedAnalyticsApp.mercategory')),
            ],
            options={
                'verbose_name': 'MER Question',
                'verbose_name_plural': 'MER Questions',
                'ordering': ['number'],
            },
        ),
    ]
