# Generated by Django 5.1.6 on 2026-03-19 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securedAnalyticsApp', '0007_officerwellbeing_owbcategory_owbquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSWCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeral', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII')], max_length=4, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'PSW Category',
                'verbose_name_plural': 'PSW Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PsychologicalSafety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Psychological Safety in the Workplace', max_length=255)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Psychological Safety in the Workplace',
                'verbose_name_plural': 'Psychological Safety in the Workplace',
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='PSWQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('text', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='securedAnalyticsApp.pswcategory')),
            ],
            options={
                'verbose_name': 'PSW Question',
                'verbose_name_plural': 'PSW Questions',
                'ordering': ['number'],
            },
        ),
    ]
