# Generated by Django 5.1.6 on 2026-03-19 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securedAnalyticsApp', '0008_pswcategory_psychologicalsafety_pswquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCLCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeral', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII')], max_length=4, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'OCL Category',
                'verbose_name_plural': 'OCL Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalCultureChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Organizational Culture and Leadership Change', max_length=255)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organizational Culture and Leadership Change',
                'verbose_name_plural': 'Organizational Culture and Leadership Change',
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='OCLQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('text', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='securedAnalyticsApp.oclcategory')),
            ],
            options={
                'verbose_name': 'OCL Question',
                'verbose_name_plural': 'OCL Questions',
                'ordering': ['number'],
            },
        ),
    ]
