# Generated by Django 5.1.6 on 2026-03-29 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securedAnalyticsApp', '0010_alter_mercategory_numeral_alter_oclcategory_numeral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_pool', models.JSONField()),
                ('responses', models.JSONField(blank=True, default=dict)),
                ('current_page', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Survey Progress',
                'verbose_name_plural': 'Survey Progress',
                'ordering': ['-updated_at'],
            },
        ),
    ]
