# Generated by Django 5.1.6 on 2026-03-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securedAnalyticsApp', '0011_surveyprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyprogress',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='in_progress', max_length=20),
        ),
        migrations.AddIndex(
            model_name='surveyprogress',
            index=models.Index(fields=['user', 'status'], name='idx_survey_user_status'),
        ),
    ]
