# Generated by Django 5.1.6 on 2026-03-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securedAnalyticsApp', '0012_add_survey_status_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='avatar',
            field=models.CharField(blank=True, choices=[('', '— No Avatar —'), ('avatar_badge.svg', 'Badge'), ('avatar_shield.svg', 'Shield'), ('avatar_star.svg', 'Star'), ('avatar_eagle.svg', 'Eagle'), ('avatar_helmet.svg', 'Helmet')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='profile_photo',
            field=models.ImageField(blank=True, default='', upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='rank',
            field=models.CharField(blank=True, choices=[('', '— Select —'), ('Officer', 'Officer'), ('Deputy', 'Deputy'), ('trooper', 'Trooper'), ('Trooper 1', 'Trooper 1'), ('Trooper 2', 'Trooper 2'), ('Trooper 3', 'Trooper 3'), ('Trooper 4', 'Trooper 4'), ('Trooper 5', 'Trooper 5'), ('Trooper 6', 'Trooper 6'), ('Ranger', 'Ranger'), ('Constable', 'Constable'), ('Detective', 'Detective'), ('Investigator', 'Investigator'), ('Deputy Inspector', 'Deputy Inspector'), ('Corporal', 'Corporal'), ('Senior Officer', 'Senior Officer'), ('Sergeant', 'Sergeant'), ('Staff Sergeant', 'Staff Sergeant'), ('Lieutenant', 'Lieutenant'), ('Captain', 'Captain'), ('Commander', 'Commander'), ('Major', 'Major'), ('Deputy Chief', 'Deputy Chief'), ('Assistant Chief', 'Assistant Chief'), ('Lieutenant Colonel', 'Lieutenant Colonel'), ('Colonel', 'Colonel'), ('Undersheriff', 'Undersheriff'), ('Chief of Police', 'Chief of Police'), ('Sheriff', 'Sheriff'), ('Commissioner', 'Commissioner'), ('Superintendent', 'Superintendent')], default='', max_length=30),
        ),
    ]
