# Generated by Django 5.1.6 on 2026-03-30 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securedAnalyticsApp', '0013_person_avatar_person_profile_photo_alter_person_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_key', models.CharField(db_index=True, max_length=10)),
                ('assessment_label', models.CharField(max_length=255)),
                ('results_data', models.JSONField(help_text='Nested structure: {"categories": [{"numeral": "I", "title": "…", "description": "…", "questions": [{"pk": 1, "number": 1, "text": "…", "answer": 5, "answer_label": "Highly Agree"}]}]}')),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Overall assessment score (populated by grading logic).', max_digits=6, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='securedAnalyticsApp.surveyprogress')),
            ],
            options={
                'verbose_name': 'Assessment Result',
                'verbose_name_plural': 'Assessment Results',
                'ordering': ['assessment_key'],
                'constraints': [models.UniqueConstraint(fields=('survey_progress', 'assessment_key'), name='unique_result_per_assessment')],
            },
        ),
    ]
