# Generated by Django 5.1.6 on 2026-03-31 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securedAnalyticsApp', '0014_assessmentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresult',
            name='anonymous_id',
            field=models.CharField(blank=True, default='', help_text='Copied from Person.anonymous_id to link user ↔ person ↔ results.', max_length=10),
        ),
        migrations.AddField(
            model_name='surveyprogress',
            name='anonymous_id',
            field=models.CharField(blank=True, default='', help_text='Copied from Person.anonymous_id to link user ↔ person ↔ results.', max_length=10),
        ),
    ]
